spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/nsrawat/microservices-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true